### ISSUE TITLE
Not starting issue, errors on canceling open orders

### ISSUE THREAD

**Issue by tofm2** [PyWaves/BlackBot#18]

**Comment by tofm2** [comment]
Hello, 

With a fresh install, here are the blackbot outputs on startup : 
python BlackBot.py sample-bot.cfg
[Nov 05 2018 14:32:32 UTC] : Reading config file 'sample-bot.cfg'
[Nov 05 2018 14:32:32 UTC] : --------------------------------------------------------------------------------
[Nov 05 2018 14:32:32 UTC] :           Address : VALID ADDRESS
[Nov 05 2018 14:32:32 UTC] :   Amount Asset ID : WAVES
[Nov 05 2018 14:32:32 UTC] :    Price Asset ID : VALID ASSET CODE
[Nov 05 2018 14:32:32 UTC] : --------------------------------------------------------------------------------
[Nov 05 2018 14:32:32 UTC] : 
[Nov 05 2018 14:32:32 UTC] : Cancelling open orders...
Traceback (most recent call last):
  File "BlackBot.py", line 122, in <module>
    BLACKBOT.cancelOpenOrders(PAIR)
  File "/home/cm/.local/lib/python2.7/site-packages/pywaves/address.py", line 858, in cancelOpenOrders
    status = order['status']
TypeError: string indices must be integers


Can someone give me some help ?

**Comment by PyWaves** [comment]
What does your config file look like?

**Comment by iammortimer** [comment]
Had the same problem, you need to switch Asset ID and Price Asset ID in the config file, then it works.
