### ISSUE TITLE
json decoder error 

### ISSUE THREAD

**Issue by sabotagebeats** [PyWaves/BlackBot#9]
`[Aug 25 2018 17:12:38 UTC] ?[1;37m:?[0;0m Cancelling open orders...
Traceback (most recent call last):
  File ".\BlackBot.py", line 122, in <module>
    BLACKBOT.cancelOpenOrders(PAIR)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pywaves\address.py", line 873, in cancelOpenOrders
    pywaves.wrapper('/matcher/orderbook/%s/%s/cancel' % ('WAVES' if assetPair.asset1.assetId == '' else assetPair.asset1.assetId, 'WAVES' if assetPair.asset2.assetId == '' else assetPair.asset2.assetId), data, host=pywaves.MATCHER)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\pywaves\__init__.py", line 131, in wrapper
    req = requests.post('%s%s' % (host, api), data=postData, headers={'content-type': 'application/json'}).json()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by PyWaves** [comment]
Are you sure you are using the latest version of pywaves?

**Comment by PyWaves** [comment]
Can you send me some example code?

**Comment by sabotagebeats** [comment]
i'm just running the standard blackbot with standard config which worked 1 month ago.

**Comment by PyWaves** [comment]
Are you setting a matcher?

sabotagebeats <notifications@github.com> schrieb am Mi., 29. Aug. 2018,
19:07:

**Comment by sabotagebeats** [comment]
`[main]
node = http://nodes.wavesnodes.com
# select the network: testnet or mainnet
network = mainnet
matcher = http://nodes.wavesnodes.com
order_fee = 300000
order_lifetime = 86400

[account]
private_key = [REDACTED]

[market]
amount_asset = [REDACTED]
price_asset = WAVES

[grid]
interval = 0.1
tranche_size = 10000000000000
grid_levels = 100
# base price calculation: LAST, BID, ASK, nnnnn (fixed constant price)
base = 5
# grid type: SYMMEMTRIC, BIDS only, ASKS, only
type = ASKS

[logging]
logfile = bot.log

`

**Comment by sabotagebeats** [comment]
sorry about the formatting i guess even when I choose insert code it makes the python comments into headers.

**Comment by PyWaves** [comment]
I see... Try with matcher.wavesnodes.com instead of nodes.wavesnodes.com
please.

sabotagebeats <notifications@github.com> schrieb am Mi., 29. Aug. 2018,
19:43:

**Comment by sabotagebeats** [comment]
works now thanks!
